Repository andrewkmag/dream-team-game-jam-2024, pull requests merged in 2024-06, with the labels that each got.

#4 Add Jump Functionality and rewrite movement to consider camera direction
  Assets/Prefabs.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Input/InputReader.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerHUDManager.cs
  Assets/Scripts/Player/PlayerHUDManager.cs.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#8 basic grappling working
  Assets/Input/Controls.inputactions
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Input/Controls.cs
  Assets/Scripts/Input/InputReader.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/grapple.cs
  Assets/Scripts/Player/grapple.cs.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#23 Dialogue Name box addons for starting animations
  Assets/Art Assets/Characters/Jam/Jam.Anim/Jam_AnimCntrl.controller
  Assets/Art Assets/UI Art/DialogueBoxName-Sticky.png
  Assets/Art Assets/UI Art/DialogueBoxName-Sticky.png.meta
  Assets/Art Assets/UI Art/DialogueBoxName.png
  Assets/Art Assets/UI Art/DialogueBoxName.png.meta
  Assets/Scenes/StartingAnimations/2_Start_Scene.unity
  Assets/Scenes/StartingAnimations/Start_Scene.unity
  Assets/Scripts/StartingSceneAnimation/DialogueManager.cs
Labels: enhancement

#24 Add basic transition between startup scenes
  Assets/Scenes/LoadSceneOrderTest/MainMenu.unity
  Assets/Scenes/StartingAnimations/Start_Scene.unity
  Assets/Scripts/StartingSceneAnimation/DialogueManager.cs
  Assets/Settings/URP-Balanced.asset
  Assets/Settings/URP-HighFidelity.asset
  Assets/Settings/URP-Performant.asset
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement

#49 Cleanup p1 of spawns
  Assets/Scenes/Planets/Donewell.unity
  Assets/Scenes/Planets/Panko.unity
  Assets/Scenes/Planets/Soyturn.unity
Labels: bug
